### ISSUE TITLE
corrplot with type = "upper" and long colname strings cuts off top labels

### ISSUE THREAD

**Issue by jharlap** [taiyun/corrplot#10]
If you corrplot a correlation matrix where variables in the data have very long names, then the plot cuts off the top labels.

For example, the following code

``` r
set.seed(123)
rmat <- matrix(runif(100), ncol = 10)
colnames(rmat) <- c("the quick brown fox jumps over the lazy dog", "and then went to get ice cream", "A", "B", "C", "D", "E", "F", "G", "H")
M <- cor(rmat)
corrplot(M, type = "upper", tl.pos = "td",
         method = "circle", tl.cex = 0.5, tl.col = 'black',
         order = "hclust", diag = FALSE)
```

Produces the following plot:
![image](https://cloud.githubusercontent.com/assets/108388/6118028/6dfb59d8-b087-11e4-8e1b-0ff9049b644d.png)

Removing the tl.cex still has the problem, yielding the following plot:
![image](https://cloud.githubusercontent.com/assets/108388/6118047/8df6bbf6-b087-11e4-938f-6bacf5debbbb.png)

Note that both plots also have a fairly excessive amount of white space to the left of the plot, but that is not the issue here.

As a workaround, I found that if I comment out [line 183 of corrplot.R](https://github.com/taiyun/corrplot/blob/master/R/corrplot.R#L183) then the problem is reduced or resolved, although the colorlegend last value (-1) gets cut off the bottom of the plot.

**Comment by smcinerney** [comment]
The other clunky workaround is `type = 'lower'`

**Comment by ssouyris** [comment]
Changing the size of the graphic devise makes the trick:

```
png("file.png")
set.seed(123)
rmat <- matrix(runif(100), ncol = 10)
colnames(rmat) <- c("the quick brown fox jumps over the lazy dog", "and then went to get ice cream", "A", "B", "C", "D", "E", "F", "G", "H")
M <- cor(rmat)
corrplot(M, type = "upper", tl.pos = "td",
         method = "circle", tl.cex = 0.5, tl.col = 'black',
         order = "hclust", diag = FALSE)
dev.off()
```
![file](https://cloud.githubusercontent.com/assets/4789097/8763423/26cadbaa-2d60-11e5-8477-82db9b95960f.png)

```
png("file2.png", width = 480,height = 600)
set.seed(123)
rmat <- matrix(runif(100), ncol = 10)
colnames(rmat) <- c("the quick brown fox jumps over the lazy dog", "and then went to get ice cream", "A", "B", "C", "D", "E", "F", "G", "H")
M <- cor(rmat)
corrplot(M, type = "upper", tl.pos = "td",
         method = "circle", tl.cex = 0.5, tl.col = 'black',
         order = "hclust", diag = FALSE)
dev.off()
```
![file2](https://cloud.githubusercontent.com/assets/4789097/8763424/4e740622-2d60-11e5-9dfe-adf57b05a984.png)

**Comment by statnmap** [comment]
Hi,
First of all, thank you for package, it allows nice plots !
I also had the same problem with long label names, using type = "lower".

I went through the code of the function to find out a fix.
At some point, there is an iterative loop calculating xlim and ylim in parallel to text length, so that labels are not cut. However, I found that the calculation of xlim and ylim in this loop did not accounted for all 'type' or 'tl.pos'. Moreover, only the text size is used after this calculation and xlim and ylim are calculated fex lines later again.
I propose to calculate xlim and ylim only in the iterative loop, accounting for all cases, including text rotation. Please find my proposition attached. I tested with all possible 'tl.pos' and it seems to work quite properly.

Because, I am here, I added two other propositions...
1/ Figure width. I added a new parameter to retrieve the suggested ratio between width and height of plots (because asp=1). I am working on linux and the 'grDevices' trick does not work. Moreover, in one of my script, the figure is in a loop for many different plot having different 'colnames' and I want the plot to be resized automatically to get nice plot without big white margins. Maybe this can help other people. At least, I added a message of suggested plot width.

2/ Bad text width calculation. For a reason I did not get, sometimes the iterative loop can not converge. Something to do with parameters of device. Default par() may have been changed somewhere and the 'oldpar' trick do not allow to retrieve a real cleaned device after running 'Corrplot' once. Thus, if reaching the maximum of the iterative loop, I added a message to suggest to clean the device and start again. This '{plot.new(); dev.off()}' helped me making the script working.

Hope this can help !
[test_corrplot.txt](https://github.com/taiyun/corrplot/files/571168/test_corrplot.txt)

**Comment by vsimko** [comment]
Finally, I fixed this issue with the help of code from @statnmap . Your code is quite cryptic, but it seems to work when I added few additional tweaks.
All the plots in our vignette now seem OK. The only part I didn't check are horizontal labels. I also tested the plots only on my Linux machine. **Please test it also on Windows.**

**Comment by cowlumbus** [comment]
First, thanks Tiayun and Viliam for the wonderful tool. It is very much needed.

I have similar issue as statnmap. I am using windows. The lastest version from CRAN or GitHub won't work. However, statnmap's code work fantastically. Thank you statnmap!

> Hi,
> [test_corrplot.txt](https://github.com/taiyun/corrplot/files/571168/test_corrplot.txt)

**Comment by cowlumbus** [comment]
Viliam, thank you for the help!. The latest version won't solve the long label name issue on Windows. statnmap's code works.

Another request, is it possible to shift the location of cl.pos to the right when I use the type=lower, tl.srt=0. Please see the attached figure, where the long label overlay with the plot.

![rl-sig-0 01](https://user-images.githubusercontent.com/25085701/51120105-61100b80-17e2-11e9-8560-530a2274c797.png)

**Comment by harrysouthworth** [comment]
I don't think the fix has been carried over to corrplot.mixed - latest version off github

**Comment by christopherball** [comment]
Please re-open this ticket, as this issue exists for corrplot.mixed.
