### ISSUE TITLE
Using plotmath in variable names

### ISSUE THREAD

**Issue by sinclairjesse** [taiyun/corrplot#20]
Is there a way of changing the variables names such that plotmath expressions could be used? I've tried adding a `labels` argument with a vector of new labels thinking that it may be passed through to `text`, but that didn't seem to work.

**Comment by vsimko** [comment]
Could you elaborate more on this ?
Or provide some example code-snippets, how it should look like.

**Comment by vsimko** [comment]
In the meantime, I found this stackoverflow question: http://stackoverflow.com/questions/35965433/r-corrplot-change-data-labels/36190501

**Comment by sinclairjesse** [comment]
Ideally,  I would be able to use plotmath expressions (e.g., use of subscripts or superscripts) as a variable name, similar to using an expression in the axis labels in base graphics. For example:

`plot(y ~ x, xlab = expression("Test"["A"]), ylab = expression("Test"^"B"))`.

Based on your answer in the stackoverflow question, colnames/rownames are used in the plotting. Something like:

`mat <- colnames(expression("Test"["A"]), expression("Test"^"B"))`

won't work.

**Comment by vsimko** [comment]
Now I understand.
I tried to implement plotmath for row/column labels but then I realized that I need some input from @taiyun - which approach is better ?

The problem is that `colnames()` and `rownames()` functions always convert their input to character even if the variable names are encoded using `expression`.

### Approach 1: colnames always parsed as expressions
- **Pros:** simple to use
- **Cons:** variable names such as "alpha" will always be rendered as greek symbol alpha
```r
M <- cor(mtcars)[1:5,1:5]
colnames(M) <- c("alpha", "beta", "alpha+beta", "a[0]", "a[beta]")
corrplot(M)
```
![image](https://cloud.githubusercontent.com/assets/7080773/14846913/644e25e6-0c66-11e6-8aa6-58f7e1bd613a.png)

### Approach 2: new parameters `xlab` & `ylab` for the `corrplot()` function
- **Pros:** control over plotmath expressions
- **Cons:** two ways for variable names specification. (1) dimnames from the original matrix, (2) xlab, ylab parameters which overrides colnames/rownames values.
```r
corrplot(M, xlab = c("alpha", "beta",
                     expression(alpha+beta),
                     expression(a[0]),
                     expression(a[beta])))
```
![image](https://cloud.githubusercontent.com/assets/7080773/14847023/d38f8134-0c66-11e6-83ce-cf47fb907d4d.png)

### Approach 3: similar to Approach 1 but using some prefix for expressions
Pros: simple to use
Cons: introducing special notation `EXPR:...`
```r
M <- cor(mtcars)[1:5,1:5]
colnames(M) <- c("alpha", "beta", "EXPR:alpha+beta", "EXPR:a[0]", "EXPR:a[beta]")
corrplot(M)
```
![image](https://cloud.githubusercontent.com/assets/7080773/14847264/f9c51a0c-0c67-11e6-9252-d2c4e28fd548.png)

**Comment by taiyun** [comment]
Approach 2 is very nice!

**Comment by vsimko** [comment]
OK, if I use Approach 3, what would be the best prefix:
- `EXPR:`
- `MATH:`
- `E:`
- or something else ?

**Comment by taiyun** [comment]
just`:`?  eg `:beta`

**Comment by vsimko** [comment]
Other options would be:
- `$` used in latex as `$math expression$`
- `=` used in spreadsheets for formulas

**Comment by taiyun** [comment]
I think anyone in `$`, `:` or `=` is OK.

**Comment by sinclairjesse** [comment]
Good solution! Thanks

**Comment by jonnez** [comment]
How do I now create a column or row name that contains just a $?

I currently get the following error (in version 0.84):
```
Error in ifelse(grepl("^[:=$]", s), parse(text = substring(s, 2)), s) :
  unimplemented type 'expression' in 'length<-'

```

**Comment by vsimko** [comment]
just use " $", e.g.
```r
M <- cor(mtcars)
rownames(M)[1] <- " $"
corrplot(M)
```
![image](https://user-images.githubusercontent.com/7080773/31249104-65f530b6-aa16-11e7-8fc7-8530006431a6.png)

**Comment by jonnez** [comment]
awesome! thanks

**Comment by gezza1232** [comment]
Hey guys! I need to write MIP-1B as a column label, where B is a beta. I can't seem to be able to merge the MIP-1 with the :beta in order to get this to look right. Do you have any ideas on how to do that?

**Comment by vsimko** [comment]
what about this:
```r
library(corrplot)
M <- cor(mtcars)
rownames(M)[1] <- ":MIP-1*beta"
corrplot(M)
```
![image](https://user-images.githubusercontent.com/7080773/45038158-fa732800-b060-11e8-9cdc-b9fcc9cfe012.png)

**Comment by gezza1232** [comment]
It worked! Thanks

**Comment by Raed-Hamed** [comment]
Hi,

I believe your solution doesn't work whenever you want to have more than one subscript associated with a variable. Is that true and is there a way to fix this?

Thanks

e.g.

M <- cor(mtcars)[1:5,1:5]
colnames(M) <- c("alpha", "beta", ":alpha+beta", ":a[1,2]", ":a[beta]")
corrplot::corrplot(M)

Also the following doesn't work:
colnames(M) <- c("alpha", "beta", ":alpha+beta", ":a"["1,2"], ":a[beta]")
