### ISSUE TITLE
Support for multiple characters when rendering NAs

### ISSUE THREAD

**Issue by vsimko** [taiyun/corrplot#55]
There is a parameter `na.label`. However, it currently only allows for a single character (default "?").
It might be useful to support more characters with some reasonable upper limit.
Example:
```r
corrplot(M2, na.label = "NA", number.cex = .7) # works from v0.76
```
![image](https://cloud.githubusercontent.com/assets/7080773/14085224/ee552258-f51e-11e5-84c6-ab2d206af6ea.png)

@taiyun Before I implement this, let's discuss the following:
- Should the limit be 2 chars or more? (I'm voting for 2)
- Should the default value be "?" or "NA" ? (I'm voting for "?")

**Comment by smcinerney** [comment]
@taiyun Before I implement this, let's discuss the following:
Should the limit be 2 chars or more? (I'm voting for 2)Should be default value be "?" or "NA" ? (I'm voting for "?") 
Well if na.label was 3 chars or more, would it be scaled or not?
Basically if you can handle 3 chars without much grief, then please do,
otherwise don't. 2 chars like 'NA' is already a huge improvement.
Beware also that you are here using 'NA' on the diagonal axis to signify
"self-correlation is not relevant, since it's always by definition 1",
not to signify "this series contains NAs, hence correlation can't be computed except 
with use="complete"".
But personally I would set/override a default na.label = "", not 
either "?" or "NA". But I don't think it matters too much what the default is
because we can override it.
 
Stephen
  
Date: Mon, 28 Mar 2016 11:01:30 -0700

**Comment by taiyun** [comment]
```
Should the limit be 2 chars or more? (I'm voting for 2)
Should the default value be "?" or "NA" ? (I'm voting for "?")
```

Agree.
