### ISSUE TITLE
Not support R3.3.2

### ISSUE THREAD

**Issue by hcp4715** [taiyun/corrplot#73]
Hi, there.
Thank you very much for developing such a good package for plotting the correlation matrix!
Unfortunately, I found this package is unavailable for R 3.3.2.
So, I am wondering will you update this package soon? 
if not, maybe I need to use the previous version of R.

Thanks again.

**Comment by vsimko** [comment]
I'm not sure what could be the problem because on my Ubuntu Xenial with R 3.3.2, I'm able to install corrplot without problems (using Rstudio). The version is however corrplot 0.77.

![image](https://cloud.githubusercontent.com/assets/7080773/20258787/8c5ac47a-aa51-11e6-8f0d-1709d4393740.png)


![image](https://cloud.githubusercontent.com/assets/7080773/20258772/7c57b074-aa51-11e6-8f7c-1b4eed29d0bd.png)

**Comment by vsimko** [comment]
What about installing it from github instead?

```r
install.packages("devtools")
devtools::install_github("taiyun/corrplot", build_vignettes = TRUE)
```

**Comment by hcp4715** [comment]
Hi, you are right. When installing it from github, it works!
Thanks a lot!
