### ISSUE TITLE
Changing aspect ratio for the plot

### ISSUE THREAD

**Issue by vsimko** [taiyun/corrplot#79]
Fabian Roger asked per email:

> Is there any way to for the output of corrplot (with is.corr = F) to be quadratic for a matrix that is not?

**Comment by vsimko** [comment]
Could you come up with a minimal reproducible example ?

**Comment by FabianRoger** [comment]
sure!

    M <- matrix(rnorm(70), ncol = 7)
    corrplot(M, is.corr = F)

here the matrix is 10 x 7. I would like to get a plot with an aspect ratio 1:1 (for the main plot, not talking about labels and legends) and hence with the single panels having an aspect ration of 0.7:1.

**Comment by vsimko** [comment]
Would this be the desired output?
```r
M <- matrix(rnorm(70), ncol = 7)
M2 <- matrix(0, nrow=10, ncol=10)
M2[,1:7] <- M
corrplot(M2, is.corr = F)
```
![image](https://cloud.githubusercontent.com/assets/7080773/22695206/3a105162-ed4a-11e6-9139-97f0b5549c7d.png)

**Comment by FabianRoger** [comment]
Depends on what you mean. Yes, it is the desired output in the sense as here the core plot has an aspect ratio of 1:1, but no, I rather would not achieve this by adding empty lines. 

I would like to get something were the (70) small squares were not quadratic but rectangular so that the main plot would be quadratic. I used to produce a custom graphic that looked like this:

![rplot02](https://cloud.githubusercontent.com/assets/5137092/22695932/b930f184-ed4c-11e6-872e-5b3021d56977.png)

**Comment by vsimko** [comment]
I now understand. Do you also want the circles to be ellipses or circles centered inside the rectangles?

**Comment by vsimko** [comment]
In my fork, I've added a new parameter `win.asp` which controls the aspect ratio of the plotted matrix.
(now it only works for "circle" and "square" methods when `win.asp != 1`)

If @taiyun is ok with this, I can merge it into the main branch.
Example:
```r
M <- matrix(rnorm(70), ncol = 7)
corrplot(M, is.corr = F, win.asp = .7)
```
![image](https://cloud.githubusercontent.com/assets/7080773/22703315/085cbe66-ed64-11e6-8823-b89cd81118da.png)

**Comment by FabianRoger** [comment]
great! that's exactly what I was looking for!

**Comment by vsimko** [comment]
merged to master

**Comment by dylanbeaudette** [comment]
Super useful, any chance `win.asp` could be extended to work with `method = 'color'`?
